### ISSUE TITLE
Pipezmod error

### ISSUE THREAD

**Issue by kellan0812** [AllTheMods/atm6-sky#411] opened 2021-06-04 22:28 UTC
![image](https://user-images.githubusercontent.com/79119286/120868475-1cfa4d00-c5cf-11eb-9e03-e8272e26a2fd.png)
If I restart the AKLIZ server 'pipez' mod gas pipe connect to 'mekanism' fission reactor port always become like the screenshot. It become normal mode not output mode and upgrade item get out.

**Comment by kts325** [comment] 2021-06-17 04:42
This is an issue caused by the structure from mekanism updating once the server restarts. Usually fixed by chunkloading the reactor

**Closed** 2021-08-18 05:08 UTC
Labels: Question
