### ISSUE TITLE
Items Not Consumed When Automating Stone Barrels

### ISSUE THREAD

**Issue by DizzyDJW** [AllTheMods/atm6-sky#74] opened 2021-03-23 04:22 UTC
**Describe the bug**

Piping an object from a Storage Drawer into a Stone Barrel with Mekanism Pipes does not consume the item to make the recipe block. Such as piping Sand into a Stone Barrel of Witch Water to get Soul Sand, doesn't consume any Sand. The same for Sky Stone Dust, Glowstone Dust, etc...
Also, a single Catalytic Reclamation Chamber upgrade in the Phytogenic Insolator stops the machine from consuming any Phyto-Gro at all. 

**To Reproduce**

1. Place a Drawer from Storage Drawers.
2. Put Sand into Drawer.
3. Use Mekanism Logistic pipes to send Sand into Stone Barrel of Lava.
4. See error.

**Expected behavior**

The block should only appear once the item is consumed.

**Comment by Vertigo81** [comment] 2021-03-23 16:40
Just came here to report the same thing.  I'm using Create pipes to fill lava into stone barrels, then Mekanism basic logistic pipes to insert dust and take out blocks.  Tested with Glowstone, Skystone and Redstone to make end/sky/netherwrack.  All don't consume the dust.

**Comment by Jkwolf25** [comment] 2021-03-24 17:19
Could it be related to how the barrel inventory works? I just noticed that when you place a crafting station next to a wooden barrel, you can see the barrels "inventory" I placed a worm in the barrels inventory slot provided by the crafting station and the barrel registered the worm as composted, however, I was able to withdraw the worm from the same inventory slot and it be "Consumed". I repeated the process until I was able to fill the barrel with one single worm to obtain a block of dirt. Hope this helps troubleshoot the issue

**Comment by WhitePhant0m** [comment] 2021-03-24 23:54
Duplicate of #38

**Closed by WhitePhant0m** 2021-03-24 23:54 UTC
Labels: Bug
