### ISSUE TITLE
Machines stop working after I log off and back in again

### ISSUE THREAD

**Issue by mckay77** [AllTheMods/atm6-sky#70] opened 2021-03-22 22:41 UTC
**Describe the bug**
Version is 1.0.4 -- SMP -- Not locally hosted

Unloading and reloading your island chunks seems to break stuff.  I dunno why.  I'm not even sure how to describe it other than that my furnace (a simple vanilla furnace) just refuses to work after disconnecting and then logging back in again.  I've tested it a number of times.  If I move the furnace to another block, it works again.  It's the same with pedestals, barrels, crucibles...  I have made new islands/teams.  Same thing every time.

**Error Message**
[Server thread/WARN] [minecraft/TileEntity]: Block entity invalid: minecraft:furnace @ BlockPos{x=24576, y=68, z=-16391}

**To Reproduce**
1. Use 'machine' and wait for it to run through a cycle.  Stand around long enough for island area to save.
2. Log off.
3. Log back in.  Nothing works.

**Expected behavior**
Maybe an unnecessary statement, but I expected my items to continue processing where they left off at after I logged back in again without the need to keep chucks loaded.

**Additional context**
1. Keep in mind, this is a hosted server for which I don't have access to the console.  The owner only saw that error message once.  Subsequent testing kicked out no error message.
2. After a full server restart things work again.
3. Force loading chunks would probably fix this, however I don't think it's a very server friendly solution.

**Comment by andremiller** [comment] 2021-03-26 18:38
I'm experiencing something similar, difficult to pinpoint the cause.

I'm also using v1.04, running on a server, and my furnace, crucible and Cobblestone Gen would sometimes stop working.

By "not working" I mean I put in coal and an iron chunk in a furnace and it doesn't start the process, or I place cobblestone into crucible and it won't melt, or the cobblestone generator doesn't output cobble into a chest anymore.  To get them going again I need to break them and place them in a different location. Just replacing them in the same spot still leaves them in a broken state.

I know these kind of problems can be difficult to track down, so just wanted to add my experience.

**Comment by oly2o6** [comment] 2021-04-04 06:20
fixed in 1.0.5+

**Closed by oly2o6** 2021-04-04 06:20 UTC
Labels: Bug
