### ISSUE TITLE
All The Modium Teleport Pad just glows instead of teleport

### ISSUE THREAD

**Issue by icon942** [AllTheMods/atm6-sky#575] opened 2021-09-10 23:57 UTC
V 1.1.8
Describe the bug
The pad does only glows when crouch right click and does not teleport

1.Place into nether or in overworld
2. Crouch right click
3. See glowing

![2021-09-07_18 57 21](https://user-images.githubusercontent.com/40743790/132928757-5a6f74fd-5f99-46e7-be54-94fa5c087438.png)
![2021-09-07_18 57 27](https://user-images.githubusercontent.com/40743790/132928758-0b683f51-1a11-4a30-adf2-a2e81afd5f14.png)

we have restarted the server multiple times as well

**Comment by Ghidhor** [comment] 2021-09-12 08:33
The mining dimension is disabled , it(teleport pad) only works in the nether in this pack

**Comment by icon942** [comment] 2021-09-12 14:12
if placed in the nether it just glows as well this is in every dimension

**Comment by oly2o6** [comment] 2021-09-30 01:28
still works for me? not sure if its because i am on a dev instance and it was just broken in 1.1.8? we will have to see but not reproducible > closing

**Closed by oly2o6** 2021-09-30 01:28 UTC
Labels: Bug
