### ISSUE TITLE
Barrel Transformation Dupe Bug

### ISSUE THREAD

**Issue by Ragelyna** [AllTheMods/atm6-sky#106] opened 2021-03-28 20:21 UTC
Barrel Transformations are making dupes

**Expected behavior**
Removing the used item on drawer that goes into barrel

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/40332465/112766813-276ef800-901c-11eb-94a5-1f71f102fb66.png)
![Screenshot_2](https://user-images.githubusercontent.com/40332465/112766863-5edda480-901c-11eb-95da-e9a472b7e21b.png)

The one that makes clay is what I made in Survival. When I saw 2048 clay in it, checked the drawer that has dust in it, it had 248 dust still in it. I removed 247 dust, put new drawer to store clay. And it made clay, but didn't use dust at all. Then I got into creative and tried other transformations like end stone, and it still duped it.

**Comment by WhitePhant0m** [comment] 2021-03-29 03:19
Duplicate of #38

**Closed by WhitePhant0m** 2021-03-29 03:19 UTC
Labels: Bug
