### ISSUE TITLE
Allthemodium ore gen

### ISSUE THREAD

**Issue by xBvrgx** [AllTheMods/atm6-sky#208] opened 2021-04-09 08:25 UTC
I started new world (1.0.6b) and traveled to the End but there was no ore generated an no chorus plants.
In the Other there is plenty of Vibranium ore so why there is no Unobtainium ore in the End?
And how to obtain Allthemodium ore? Description says it is generating in ocean biome but it is skyblock and there is no overworld ore gen :(

**Comment by elbim** [comment] 2021-04-10 15:03
You get Allthemodium Ore Pieces on 0.2% by running gravel through a Netherite Mesh. Same for Unobtainium Ore Pieces (0.2%) and Chorus Flowers (10%) by processing Crushed End Stone through a Netherite Mesh.

**Comment by xBvrgx** [comment] 2021-04-10 16:04
Yeah, I know, but in previous version I could find Unobtainium, Inferium ore and Chorus Flowers all over the place in the End.

**Comment by MelanX** [comment] 2021-04-11 19:15
I think this is caused by Skyblock Builder. When updating the pack, the new version of Skyblock Builder should be in the pack which fixes this.

**Comment by Pdiddy973** [comment] 2021-04-29 05:36
should be fixed in 1.0.8

**Closed by Pdiddy973** 2021-04-29 05:36 UTC
Labels: Question
