### ISSUE TITLE
i updated to the new atm to the sky version and cant load world from older atm to the sky version

### ISSUE THREAD

**Issue by qussaif100** [AllTheMods/atm6-sky#551] opened 2021-08-27 21:25 UTC
im on a single player world and i updated from v1.1.7 to v1.1.8 and when i try to load my world it says incomplete set of tags received from server. Please contact server operator. even though im on single player it gives me a back to server list button
and the second time i try to load it it says "errors in currently selected datapacks prevented the world from loading u can either try to load it with only the vanilla data pack ("safe mode", or go back to the title screen and fix it manually)" and even when i click safe mode nothing happens

![Screenshot 2021-08-28 002439](https://user-images.githubusercontent.com/88863855/131190146-edd8b12e-bf72-44d1-ac27-a7dc7f31993e.png)

**Comment by MushuPlatypus** [comment] 2021-08-28 10:27
Tried to do a fresh install but still get the above error

**Comment by bribri69** [comment] 2021-08-28 14:37
Hello,
Had the same pb and i removed the mod observable.
It works now.
Hope it's not a coincidence ! lol

**Comment by bribri69** [comment] 2021-08-29 07:28
It was a coincidence ! 😭

**Comment by Gustaaaguiar** [comment] 2021-08-29 13:23
Now I got the same problem again :c 
I tried to remove the mod observable but didn't work :/

**Comment by bribri69** [comment] 2021-08-29 15:07
Like i said, unfortunately it was a coincidence, it's just that it works when i completely reload the modpack...

**Comment by G4ming69** [comment] 2021-08-29 15:41
never update ATM6 omfg, all times bugs, performance drops ......

**Comment by oly2o6** [comment] 2021-08-31 04:40
There was an issue where the server files were not removing JER (just enough resources) from the mods as that mod cannot go on the server, please try removing that mod and see if it fixes your issues

**Comment by qussaif100** [comment] 2021-08-31 10:35
> There was an issue where the server files were not removing JER (just enough resources) from the mods as that mod cannot go on the server, please try removing that mod and see if it fixes your issues

ill try to do that and see if its fixed, thx

**Comment by qussaif100** [comment] 2021-08-31 10:53
> There was an issue where the server files were not removing JER (just enough resources) from the mods as that mod cannot go on the server, please try removing that mod and see if it fixes your issues

didnt work, i removed JER from the mods file and i still get the error

**Comment by Kevin-Marsh** [comment] 2021-09-01 05:10
I had the same issue. Did some research and found that it is being caused by the version of Cyclic mod that is in the pack. I updated to the latest Cyclic released yesterday to fix the issue and my save is back to working now. Can you try that?

**Comment by qussaif100** [comment] 2021-09-01 10:10
> I had the same issue. Did some research and found that it is being caused by the version of Cyclic mod that is in the pack. I updated to the latest Cyclic released yesterday to fix the issue and my save is back to working now. Can you try that?
> 
> Edit: [Lothrazar/Cyclic#1906](https://github.com/Lothrazar/Cyclic/issues/1906) is the Cyclic bug report that should be applicable for anyone that needs it.

kk

**Comment by qussaif100** [comment] 2021-09-01 10:23
> I had the same issue. Did some research and found that it is being caused by the version of Cyclic mod that is in the pack. I updated to the latest Cyclic released yesterday to fix the issue and my save is back to working now. Can you try that?
> 
> Edit: [Lothrazar/Cyclic#1906](https://github.com/Lothrazar/Cyclic/issues/1906) is the Cyclic bug report that should be applicable for anyone that needs it.

it worked, thx

**Comment by casultran** [comment] 2021-09-06 17:08
> 
> 
> I had the same issue. Did some research and found that it is being caused by the version of Cyclic mod that is in the pack. I updated to the latest Cyclic released yesterday to fix the issue and my save is back to working now. Can you try that?
> 
> Edit: [Lothrazar/Cyclic#1906](https://github.com/Lothrazar/Cyclic/issues/1906) is the Cyclic bug report that should be applicable for anyone that needs it.

Can also confirm! This fix worked fine for me.

**Comment by oly2o6** [comment] 2021-09-06 21:16
closing this in favour of #564 so we have 1 open for people to look at with a fix, next pack version will fix it regardless thanks to kevin for tracking it down

**Closed by oly2o6** 2021-09-06 21:16 UTC
Labels: Bug, Confirmed, Waiting for reply
