### ISSUE TITLE
Compact Mahou

### ISSUE THREAD

**Issue by HKQ889** [AllTheMods/atm6-sky#288] opened 2021-04-21 06:52 UTC
Don't build the caliburn sword lake in a compact machine it breaks the unbreakable ground to build the lake and you have access to the void and other compact machines you built

**Comment by Vany** [comment] 2021-04-21 19:32
In additions to this, if you really wanna escape from machine, you can place elevator with an enchanted pedestal block placer or just teleport outside via teleportation wand. And then install ars nouveau portals around your ugly cube.
https://www.youtube.com/watch?v=oPgqfQzZck0

**Comment by Attila1616** [comment] 2021-04-21 19:54
Or just use the "Rod of Elevation" from Cyclic which will teleport you to the top of the cube...

**Comment by oly2o6** [comment] 2021-05-02 08:20
yeah you can even vanilla enderpearl out of a compact machine so im going to close this

**Closed by oly2o6** 2021-05-02 08:20 UTC
Labels: Bug

**Comment by stepsword** [comment] 2021-05-02 16:36
these are on different versions but this is probably a duplicate of this https://github.com/CompactMods/CompactMachines/issues/423
