### ISSUE TITLE
Two different types of osmium pieces and chunks

### ISSUE THREAD

**Issue by nddragoon** [AllTheMods/atm6-sky#28] opened 2021-03-11 16:12 UTC
There are currently two separate different types of osmium ore pieces and chunks. One from Ex Nihilo Sequentia and the other added with KubeJS. they both appear by sieving and they both can be processed the same way. Would be nice to unify both

**Comment by starforcraft** [comment] 2021-03-11 16:13
Duplicate of #14

**Closed** 2021-03-11 20:50 UTC
Labels: KubeJS
