### ISSUE TITLE
Infinit Dirt bug

### ISSUE THREAD

**Issue by tp0070** [AllTheMods/atm6-sky#47] opened 2021-03-20 11:24 UTC
I found a bug 
put a Wooden Barrel and a Chest. Connect it with  Basic Logistical Transporter configure pip 5 of them and set to pull item from chest, put sapling in the chest and it will consume 0 Tree Sapling to make a Dirt instead of 8
![2021-03-20_22 13 28](https://user-images.githubusercontent.com/81018237/111873121-bbf8ab00-89c9-11eb-876d-f565af967fd4.png)

**Comment by Uginsecond** [comment] 2021-03-20 19:38
As I wrote before :) - https://github.com/AllTheMods/atm6-sky/issues/38

**Comment by WhitePhant0m** [comment] 2021-03-20 19:38
Duplicate of #38

**Closed by WhitePhant0m** 2021-03-20 19:38 UTC
Labels: Bug
